# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: chaimongkolpan
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: jamsai-16y-mtl
service: jamsai-16y-mtl

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: api
          